import {icons} from "@/constants/icons";

export const settings = [
    {
        title: "Profile",
        icon: icons.user,
    },
    {
        title: "Notifications",
        icon: icons.bell,
    },
    {
        title: "Security",
        icon: icons.security,
    },
    {
        title: "Help Center",
        icon: icons.helpCenter,
    },
    {
        title: "Invite Friends",
        icon: icons.inviteFriends,
    },
]

export const languages = [
    {code: "af-ZA", name: "Afrikaans (South Africa)"},
    {code: "ar-AE", name: "Arabic (United Arab Emirates)"},
    {code: "ar-SA", name: "Arabic (Saudi Arabia)"},
    {code: "be-BY", name: "Belarusian (Belarus)"},
    {code: "bg-BG", name: "Bulgarian (Bulgaria)"},
    {code: "bn-BD", name: "Bengali (Bangladesh)"},
    {code: "ca-ES", name: "Catalan (Spain)"},
    {code: "ch-GU", name: "Chamorro (Guam)"},
    {code: "cn-CN", name: "Chinese (China)"},
    {code: "cs-CZ", name: "Czech (Czech Republic)"},
    {code: "cy-GB", name: "Welsh (United Kingdom)"},
    {code: "da-DK", name: "Danish (Denmark)"},
    {code: "de-AT", name: "German (Austria)"},
    {code: "de-CH", name: "German (Switzerland)"},
    {code: "de-DE", name: "German (Germany)"},
    {code: "el-GR", name: "Greek (Greece)"},
    {code: "en-AU", name: "English (Australia)"},
    {code: "en-CA", name: "English (Canada)"},
    {code: "en-GB", name: "English (United Kingdom)"},
    {code: "en-IE", name: "English (Ireland)"},
    {code: "en-NZ", name: "English (New Zealand)"},
    {code: "en-US", name: "English (United States)"},
    {code: "eo-EO", name: "Esperanto"},
    {code: "es-ES", name: "Spanish (Spain)"},
    {code: "es-MX", name: "Spanish (Mexico)"},
    {code: "et-EE", name: "Estonian (Estonia)"},
    {code: "eu-ES", name: "Basque (Spain)"},
    {code: "fa-IR", name: "Persian (Iran)"},
    {code: "fi-FI", name: "Finnish (Finland)"},
    {code: "fr-CA", name: "French (Canada)"},
    {code: "fr-FR", name: "French (France)"},
    {code: "ga-IE", name: "Irish (Ireland)"},
    {code: "gd-GB", name: "Scottish Gaelic (United Kingdom)"},
    {code: "gl-ES", name: "Galician (Spain)"},
    {code: "he-IL", name: "Hebrew (Israel)"},
    {code: "hi-IN", name: "Hindi (India)"},
    {code: "hr-HR", name: "Croatian (Croatia)"},
    {code: "hu-HU", name: "Hungarian (Hungary)"},
    {code: "id-ID", name: "Indonesian (Indonesia)"},
    {code: "it-IT", name: "Italian (Italy)"},
    {code: "ja-JP", name: "Japanese (Japan)"},
    {code: "ka-GE", name: "Georgian (Georgia)"},
    {code: "kk-KZ", name: "Kazakh (Kazakhstan)"},
    {code: "kn-IN", name: "Kannada (India)"},
    {code: "ko-KR", name: "Korean (South Korea)"},
    {code: "ky-KG", name: "Kyrgyz (Kyrgyzstan)"},
    {code: "lt-LT", name: "Lithuanian (Lithuania)"},
    {code: "lv-LV", name: "Latvian (Latvia)"},
    {code: "ml-IN", name: "Malayalam (India)"},
    {code: "mr-IN", name: "Marathi (India)"},
    {code: "ms-MY", name: "Malay (Malaysia)"},
    {code: "ms-SG", name: "Malay (Singapore)"},
    {code: "nb-NO", name: "Norwegian Bokmål (Norway)"},
    {code: "nl-BE", name: "Dutch (Belgium)"},
    {code: "nl-NL", name: "Dutch (Netherlands)"},
    {code: "no-NO", name: "Norwegian (Norway)"},
    {code: "pa-IN", name: "Punjabi (India)"},
    {code: "pl-PL", name: "Polish (Poland)"},
    {code: "pt-BR", name: "Portuguese (Brazil)"},
    {code: "pt-PT", name: "Portuguese (Portugal)"},
    {code: "ro-RO", name: "Romanian (Romania)"},
    {code: "ru-RU", name: "Russian (Russia)"},
    {code: "si-LK", name: "Sinhala (Sri Lanka)"},
    {code: "sk-SK", name: "Slovak (Slovakia)"},
    {code: "sl-SI", name: "Slovenian (Slovenia)"},
    {code: "sq-AL", name: "Albanian (Albania)"},
    {code: "sr-RS", name: "Serbian (Serbia)"},
    {code: "sv-SE", name: "Swedish (Sweden)"},
    {code: "ta-IN", name: "Tamil (India)"},
    {code: "te-IN", name: "Telugu (India)"},
    {code: "th-TH", name: "Thai (Thailand)"},
    {code: "tl-PH", name: "Tagalog (Philippines)"},
    {code: "tr-TR", name: "Turkish (Turkey)"},
    {code: "uk-UA", name: "Ukrainian (Ukraine)"},
    {code: "vi-VN", name: "Vietnamese (Vietnam)"},
    {code: "zh-CN", name: "Chinese (Simplified, China)"},
    {code: "zh-HK", name: "Chinese (Hong Kong)"},
    {code: "zh-SG", name: "Chinese (Singapore)"},
    {code: "zh-TW", name: "Chinese (Traditional, Taiwan)"},
    {code: "zu-ZA", name: "Zulu (South Africa)"}
]